version: "3"
services:
  db:
    image: postgres:12.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  rabbit:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      NAME: rabbitmq
    networks:
      - default

networks:
  default:
    driver: bridge